{% set version = "0.6.0.84" %}
{% set lib_version = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2] %}
{% set platform = "placeholder" %}  # [not (linux64 or aarch64)]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}    # [aarch64]
{% set extension = "tar.xz" %}

{% set cuda_compiler_version = cuda_compiler_version|default("None") %}
{% set cuda_major = environ.get("cuda_compiler_version", "13.0").split(".")[0] %}

package:
  name: libcublasmp-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cublasmp/redist/libcublasmp/{{ platform }}/libcublasmp-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
  sha256: 214a439031cc53be7d02961651e5e6ee520d80ab09b772d5a470e678477a6c57  # [linux64 and (cuda_compiler_version or "").startswith("12")]
  sha256: f3892486ac72649ab5e140fd1466421e5638ce23a56a5360a42f32450fcfbf83  # [linux64 and (cuda_compiler_version or "").startswith("13")]
  sha256: 6af07f02ed01eee761509ad5c733a7196520f09ce036d5d047f38a1768287080  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
  sha256: 9c3ea75c2a2705cb415d37316a6f540dbeb021ac3dc7bf0404dac314eb098aa0  # [aarch64 and (cuda_compiler_version or "").startswith("13")]

build:
  number: 0
  skip: true  # [cuda_compiler_version in (None, "None") or (cuda_compiler_version or "").startswith("11")]
  skip: true  # [not (linux64 or aarch64)]
  script:
    - check-glibc lib/*.so.*
    - cp -rv include $PREFIX
    - cp -rv lib $PREFIX

requirements:
  build:
    - cf-nvidia-tools 1   # [linux]

outputs:
  - name: libcublasmp
    build:
      ignore_run_exports:
        - cuda-version
      run_exports:
       # potentially breaking changes with every minor version until 1.0.0
        - {{ pin_subpackage("libcublasmp", max_pin="x.x") }}
      missing_dso_whitelist:
        - "*libcuda.so*"
    files:
      - lib/libcublasmp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}
        - libcublas
        - nccl
        - libnvshmem3
      run:
        - {{ pin_compatible("cuda-version", max_pin="x") }}
        - libcublas
        - nccl
        - libnvshmem3
    test:
      commands:
        - test -L $PREFIX/lib/libcublasmp.so.0
        - test -f $PREFIX/lib/libcublasmp.so.{{ lib_version }}
    about:
      home: https://docs.nvidia.com/cuda/cublasmp/
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
      summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
      description: |
        NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
        cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
      doc_url: https://docs.nvidia.com/cuda/cublasmp/

  - name: libcublasmp-dev
    build:
      ignore_run_exports:
        - cuda-version
      run_exports:
        - {{ pin_subpackage("libcublasmp", max_pin="x") }}
    files:
      - lib/libcublasmp.so
      - include/cublasmp.h
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_subpackage("libcublasmp", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/cublasmp.h
        - test -L $PREFIX/lib/libcublasmp.so
    about:
      home: https://docs.nvidia.com/cuda/cublasmp/
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
      summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
      description: |
        NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
        cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
      doc_url: https://docs.nvidia.com/cuda/cublasmp/

about:
  home: https://docs.nvidia.com/cuda/cublasmp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
  summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
  description: |
    NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
    cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
  doc_url: https://docs.nvidia.com/cuda/cublasmp/

extra:
  recipe-maintainers:
    - almogsegal
    - mrogowski
    - conda-forge/cuda
  feedstock-name: libcublasmp
