{% set version = "0.5.0.898" %}
{% set lib_version = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2] %}
{% set platform = "placeholder" %}  # [not (linux64 or aarch64)]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}    # [aarch64]
{% set extension = "tar.xz" %}

{% set cuda_compiler_version = cuda_compiler_version|default("None") %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0] %}

package:
  name: libcublasmp-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cublasmp/redist/libcublasmp/{{ platform }}/libcublasmp-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
  sha256: e8bc831d743bbbf5f5af8b728ab4da74acdcea37c4ee1022e63f8f537d5488a2  # [linux64 and (cuda_compiler_version or "").startswith("12")]
  sha256: 6e548a11bd6ba6c4aef77c9d1c16bdc39b7ec268547f856c5dab39085fbb7fd4  # [aarch64 and (cuda_compiler_version or "").startswith("12")]

build:
  number: 0
  skip: true  # [cuda_compiler_version in (None, "None") or (cuda_compiler_version or "").startswith("11")]
  skip: true  # [not (linux64 or aarch64)]
  script:
    - check-glibc lib/*.so.*
    - cp -rv include $PREFIX
    - cp -rv lib $PREFIX

requirements:
  build:
    - cf-nvidia-tools 1   # [linux]

outputs:
  - name: libcublasmp
    build:
      run_exports:
        - {{ pin_subpackage("libcublasmp", max_pin="x") }}
      missing_dso_whitelist:
        - "*libcuda.so*"
    files:
      - lib/libcublasmp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}
        - libcublas    # [(cuda_compiler_version or "").startswith("12")]
        - cudatoolkit  # [(cuda_compiler_version or "").startswith("11")]
        - nccl
        - libnvshmem3
      run:
        - {{ pin_compatible("cuda-version", max_pin="x") }}
        - libcublas    # [(cuda_compiler_version or "").startswith("12")]
        - cudatoolkit  # [(cuda_compiler_version or "").startswith("11")]
        - nccl
        - libnvshmem3
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -L $PREFIX/lib/libcublasmp.so.0
        - test -f $PREFIX/lib/libcublasmp.so.{{ lib_version }}
    about:
      home: https://docs.nvidia.com/cuda/cublasmp/
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
      summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
      description: |
        NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
        cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
      doc_url: https://docs.nvidia.com/cuda/cublasmp/

  - name: libcublasmp-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcublasmp", max_pin="x") }}
    files:
      - lib/libcublasmp.so
      - include/cublasmp.h
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x") }}
        - {{ pin_subpackage("libcublasmp", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/include/cublasmp.h
        - test -L $PREFIX/lib/libcublasmp.so
    about:
      home: https://docs.nvidia.com/cuda/cublasmp/
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
      summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
      description: |
        NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
        cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
      doc_url: https://docs.nvidia.com/cuda/cublasmp/

about:
  home: https://docs.nvidia.com/cuda/cublasmp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
  summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
  description: |
    NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
    cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
  doc_url: https://docs.nvidia.com/cuda/cublasmp/

extra:
  recipe-maintainers:
    - almogsegal
    - mrogowski
    - conda-forge/cuda
  feedstock-name: libcublasmp
